apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-enclave-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-enclave
  template:
    metadata:
      labels:
        app: nginx-enclave
    spec:
      containers:
      - name: nginx-container
        image: nerdysrisha/nginx-nitro-enclave:latest
        resources:
          limits:
            aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-2Mi: 512Mi  # Reduced from 768Mi for nginx
            cpu: 500m             # Increased CPU for nginx
            memory: 1Gi           # Added memory limit
          requests:
            aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-2Mi: 512Mi
            memory: 512Mi
        volumeMounts:
        - mountPath: /dev/hugepages
          name: hugepage
          readOnly: false
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages-2Mi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
